var JSALLDATA = {
    IZmarquee		: 1,
    IZmeteo			: 1,
    IZMtoPRYRS		: 0,
    IZforHOME		: 0,
    IZaddZerosAMPM	: 0,
    IZ5BoxesOnly	: 1,
    IZDohaSaver		: 0,
    IZIshaSaver		: 0,
    IZJanazatShow	: 0,
    DHRxminASR		: 0,
    JomoaIzInLogo	: 1,    
    IZ5minAzkar		: 0,
    IZVrMiddleNames	: 0,
    IZVrNoNEXTNoJMA	: 1,
    FontoTIMES		: 'FONTO',
    FontoCLOKEN		: 'FONTO',
    FontoAZKAR		: 'SULTAN',
    IZAzkarSABAH	: 1,
    IZAzkarASR		: 1,
    IZAzkarMAGRIB	: 1,
    IZAzkarISHA		: 0,
    userMonths		: 2,
    IZ1MinCounter	: 1,
    IZSCounterEnlarge : 1,
    IZIqamaScreen	 : 1,
    IZJOMOAon		 : 0,
    IZHIJRI          :1,
    IZCORAN          :1,
    IZMIHRAB         :1,
    IZMINARET        :1,
    IZAMPLIEXTERNE   :1,
    IZAMPLIINTERNE   :1,
    IZLOG            :1,
    IZSALATNABI      :1,
    IZSTROB          :1,
    IZROLLER         :1,
    JS_STROB_DURATION:3,
    JS_SELECTEDCORANDELAY:15,
    DL_AMPLIEXT :60000,
    DL_AMPLIINT :180000,
    DL_MIHRAB  :120000,
    DL_SALATNABI:160000,
    JS_PlayCoranFjr  :0,
    JS_PlayCoranThuhr:0,
    JS_PlayCoranAsr  :0,
    JS_PlayCoranMaghreb:1,
    JS_PlayCoranIsha  :1,
    JS_PlayCoranJomoaa:0,
    JS_BEEP_ON        :1,
    DAY_SALATNABI     :4,
    JS_DELAY_ROLLER   :300000,
    IZPRAYERCOUNTDOWN  :1,
    AZKARSLIDEDELAY    :30000,
    }